rainlab/user-plugin

components/Session.php, lang/en/lang.php, lang/fa/lang.php, lang/hu/lang.php, lang/pt-br/lang.php, lang/ru/lang.php
Add flash message to logout dialog
=> Add flash message to logout dialog

models/User.php
I think that comment of Tim Savory (and others) on https://octobercms.com/plugin/rainlab-user is correct.
The only way to store a username field on register form is to add it on $fillable.
Is this approach correct?
=> Username on Login form

lang/cs/lang.php
Update cs_CZ locale - add groups, remove locations
=> Update cs_CZ locale - add groups, remove locations

README.md
I met a user that didn't know of the requirements of the plugin and expressed frustration at the lack of documentation.
=> Clarification of plugin requirements

lang/cs/lang.php
Update cs_CZ locale by new features - trashing, banning, restoring, unbanning.
Remove redundant `register` field.
=> Update cs_CZ locale

Plugin.php
Fix permission key. All keys start with 'access' prefix.
=> Fix permission key. All keys start with 'access' prefix.

components/Session.php
On logout get error `Class 'RainLab\User\Components\Event' not found`
=> Add use Event

lang/en/lang.php, lang/pt-br/lang.php, models/user/fields.yaml
1. Translate the 'groups' lang key in pt-br/lang.php
2. Add the two missing keys for 'create_password' and 'create_password_comment' in pt-br/lang.php
3. Add the missing translation in fields.yaml for the text 'Block all outgoing mail sent to this user.'
4. Add the key 'block' in en/lang.php
5. Add the key 'block' in pt-br/lang.php
=> add the missing translations for pt-BR language in user fields and the missing key for 'Block all outgoing mail sent to this user.'

controllers/users/config_filter.yaml
Comes handy if there is confusion which users have been activated.
=> Added activated filter in backend users list

components/Account.php, components/account/register.htm
Sets the value of `allow_registration` to the `$canRegister` property of the component and passes it to the page vars for rendering the component.
Fixes #135
=> Pass canRegister setting to partials

components/account/default.htm, components/account/register.htm
=> hide "Registration" title when registrations are disabled

components/account/register.htm
Checks whether the login attribute is "username" and adds the required input field to register.htm. 
Issue reference: #284
=> Add username to register.htm if loginAttribute is username.

README.md
This should also be fixed on the plugin's marketplace page:
http://octobercms.com/plugin/rainlab-user
=> Fixed resetPassword component name

lang/es/lang.php
Missing translations are added in Spanish
=> Improve Spanish translations

updates/version.yaml
https://github.com/rainlab/user-plugin/issues/378
=> Release a new version

controllers/Users.php
Displays banned user in user list as red entry.
=> Mark banned user in user list

components/Account.php, lang/en/lang.php, lang/it/lang.php
If User settings > Activation mode = Administrator
No message is displayed after user registration
=> add flash message if activation by administrator

config/config.php, models/Settings.php
Moving initial values to file based configuration so that they can be kept in the consuming application's source control.
See conversation here https://octobercms.slack.com/archives/C09864473/p1606461477304800
=> Expand file based configuration options

README.md
add an explanation of how to send notification emails due to its replacement of the feature in version 1.4
=> Update notification changes within README

components/account/default.htm, components/account/signin.htm
Because of heading in register.htm partial, this may be same for signin.htm partial, to stay on same policy... When you tried to customize partials, in old code you need to update default.htm a register.htm partial, instead of customization of partial for specific type of action.
=> Same code practice for partials

components/Registration.php
So we can check if registration is enabled/disabled in our theme.
=> Adds a canRegister method to the Registration component

Plugin.php, controllers/users/_list_toolbar.php, controllers/users/preview.php
Added rainlab.user.timelines to registerPermissions and registerNavigation.
Hide the "user groups" button if the administrator does not have access
=> Timelines and user groups permissions

models/User.php
=> Add getAuthPasswordName method to User model for compatibility with October CMS v4
