models/User.php

When the username is not used, the email is substituted. But when email is empty, it throws "The username field is required." because it uses 'username' attribute validation rule.
https://github.com/rainlab/user-plugin/blob/master/models/User.php#L91
Solution is fire email rule at first place.

Runs email validation at first, because we always need email, even if username is empty

---

Plugin.php
updates/version.yaml

If a Backend-User is not allowed to "Manage Users" he should also not be able to access the Settings part of the Userplugin!

Require permission on settings page too

---

components/Account.php

After update to [Build 273](https://octobercms.com/forum/post/update-to-modelsave-method) the account profile doesn't save data.

Fix onUpdate account for Build 273

---

Plugin.php
lang/en/lang.php
lang/fr/lang.php

Ability to hide the settings menu items for certain groups of admins.
We needed this ability in our project and found no way of hiding the plugin setting menu while keeping the top menu user item.
So now settings permissions are independant of the user management menu permissions.

Add permissions for user plugin's settings

---

models/usergroup/columns.yaml

When the sort icon is clicked on the USERS column of the UserGroup list an error is returned. Subsequent requests to this page will result an in error because it is saved as the users preference to sort by this column. Setting the sortable attribute to false for this column resolves this problem.

Avoid error when clicking sort on users_count column

---

README.md
components/Session.php

Added rainlab.user.logout event for custom managing while user logged out. 
Can be useful for deleting session data, cache etc.

Add rainlab.user.logout event

---

controllers/users/_preview_scoreboard.htm
lang/en/lang.php
lang/fr/lang.php

Missed that one the other day. If I'm not wrong the logic should be : 
`name` == _first name_ == _Prénom_
`surname` == _last name_ == _Nom_
If that's the case, it requires to invert the original french translation.
Shortened the `username` field to something more common too.

Fix Inverted name/surname french translation + externalize online status strings

---

lang/en/lang.php

'your nominated email address' doesn't make any sense, it should be 'your email address' or even 'your provided email address'.

Remove extraneous 'nominated'

---

README.md

I guess `onCheckEmail` should be defined inside the page code, so I updated the document accordingly. Please correct me if my suggestion is wrong.

Specify where onCheckEmail should be defined

---

components/Account.php

There was no validation that password field has to be confirmed. If there is no `password_confirmation` field on frontend than you already have code below implemented so this validation should pass.
````
if (!array_key_exists('password_confirmation', $data)) {
$data['password_confirmation'] = post('password');
}
```

fix validate password confirmation

---

README.md
components/Account.php

Adds `'rainlab.user.beforeRegister'` and `'rainlab.user.register'` events to registration processing of the Account component. Fixes #249

Add events for registering users

---

controllers/UserGroups.php

Allows extensions of UserGroups controller to use relations.
Like:
UserGroups::extend(function (GroupController $controller) {
$controller->relationConfig =
Yaml::parse(File::get('plugins/kurtjensen/profile/controllers/usergroups/config_relation.yaml'));
});

Add property $relationConfig

---

components/Session.php
lang/en/lang.php

Is there also a way to hide the `groupsAllowed` inspector option if `ALL` or `GUEST` is selected and only show it if `security` is set to `USER`?
Refers to issue https://github.com/rainlab/user-plugin/issues/127

Add group allowance to session security

---

components/ResetPassword.php

This is a simple fix to correct what I think is an oversight in the password reset process. I believe guest accounts should be treated the same as there being no account. It's confusing to users if they're not sure if they registered, as they can run through a password reset as though they had a registered account, but they still can't log in after that.

Prevent guest accounts from resetting the account password

---

views/mail/restore.htm

Just a simple typo fix in the default password reset template.

Fix typo in password reset mail template

---

components/Session.php

If redirect on the session component is set to - none - then the page ends in an infinite redirect loop. This adds a check and throws an exception rather than redirecting in that specific case.

Fix infinite redirect loop when redirect property set to - none -

---

Plugin.php

I came across this while troubleshooting an issue wherein the `new_user` email was not being sent upon registration, despite having the Notify plugin installed and a corresponding notification rule created.  After making this change locally, the problem was resolved, leading me to believe that this may have been a simple oversight when the change to the Notify plugin was made.

Bind `rainlab.user.register` event in Plugin.php

---

Plugin.php
controllers/usergroups/_list_toolbar.htm
controllers/users/_list_toolbar.htm

Supersedes #321 
- Added sidemenu items for users and groups
- removed 'back to users' button from groups toolbar
- removed 'groups' button from users toolbar

Separate user and group management

---

components/Account.php

Fixes bug where an empty redirect property will still result in a redirect
```php
// $property = '';
if (strlen($property) && !$property) { // Will evaluate as 0 && true
return;
}
```

Fix redirect bug

---

views/mail/invite.htm

Prevent html characters from being encoded. A password containing html characters is currently being encoded.
For example, the password `123&test` is being sent to the user as `123&amp;test`

Use raw filter on password

---

components/Account.php
lang/en/lang.php
models/Settings.php
models/User.php
models/settings/fields.yaml
models/user/columns.yaml
models/user/fields.yaml
updates/users_add_ip_address.php
updates/version.yaml

Introduces IP logging for user accounts. The registration throttle prevents an issue where bots spam registration with dummy accounts.

IP logging and Registration throttle

---

components/Account.php

I have had several instances of users trying to log in and authenticating failing because they have whitespace in their email address which is obviously difficult to see on the screen. While this is technically a case of user error, I think that adding whitespace trimming would make the login system more user friendly to less technical users.

Add whitespace trimming to login

---

components/Account.php

This allows to split the account edition into multiple partials, and still uses the onUpdate handler, having for instance one page only for e-mail editing.
Before, error was thrown line 422 when missing password field.

No longer require password field for onUpdate handler

---

controllers/Users.php
controllers/users/_preview_toolbar.htm
lang/en/lang.php
models/User.php

During my first OctoberCMS project, I kept forgetting the user password for my test user. Having forgotten these passwords I had to manually keep clearing the user throttle table. Adding this will allow a quick way to remove the suspension on a user account not just useful for testing but also for further use within an application.

Unsuspend a user from user preview

---

Plugin.php
README.md
controllers/users/_list_toolbar.htm
controllers/users/_preview_toolbar.htm

Added view extension events that can be used to extend the toolbars on the user listing and preview page. This supersedes PR #391.

Feature to extend user preview and listing toolbars

---

README.md

Tests are run with GitHub Actions now

Replace obsolete status badge

---

components/Account.php

Upon successfully registering a user, they are always redirected to their intended page, even when they are not activated. 
This is confusing, because that intended page is usually behind a login wall, which they can't login to yet while their account isn't activated. 
More elegant solution would be to only redirect the user to their intended page if they are automatically activated (and therefore logged in). If they are not, it might make more sense to redirect them to a page specified in the component's redirect parameter.

Fix intended redirect on register success

---

classes/AuthManager.php
components/ResetPassword.php

This pull request creates a new event that will help 3rd party plugins extend the main user query used by the AuthManager.
The Reset Password was also updated to use the AuthManager's user query triggering the new event like the other components

New event rainlab.user.extendUserAuthQuery

---

LICENCE.md
README.md
classes/AuthManager.php
classes/authmanager/HasBearerToken.php
classes/authmanager/HasJwtTokens.php
components/Session.php
composer.json
lang/en/lang.php
models/User.php

The following PR adds basic JWT support to Auth Manager, targeting v2.1 of this plugin.
Returns a bearer token (JWT) that can be used to authenticate the current user for 1 hour.
```php
public function token()
{
return Auth::getBearerToken();
}
```
Verifies a supplied bearer token, and if valid, sets the authenticated user.
```php
function onStart()
{
if ($jwtToken = Request::bearerToken()) {
Auth::checkBearerToken($jwtToken);
}
}
```
Now includes a `token()` method for generating a new token for the signed in user.
```twig
url = "/api/login"
[account]
[session]
==
{% do response(
ajaxHandler('onSignin').withVars({
token: session.token()
})
) %}
```
The `verifyToken` property is used to verify the token in the headers (`Authorization: Bearer <TOKEN>`).
```twig
url = "/api/login/renew" …
```

Release 2.1 - Adds JWT support

---

models/user/UserImport.php

I wanted to use import, but i get error "Error: Class "RainLab\User\Models\User\UserImport"",
when i inspected the code it's look like there is some typos and missing field.
After this changes it's works.

Fixing typos and missing rules field in UserImport model

---

models/User.php

Avoid array_merge error when passing an array with a NULL value.
Append when asking a password recovery
TypeError: array_merge(): Argument #1 must be of type array, null given in /plugins/rainlab/user/models/User.php:434

Fix : Notifications array_merge when array with NULL value

---

components/Registration.php
models/user/HasModelAttributes.php

Fixes #592 and also trims extra white space when getting full_name, if last_name is empty.

Last name is not required
